id: P8F12ACAD
initial_creation_type: input
source_metadata:
  title: Auspiciousness Series
  language: de
  description: 'A selection of texts on the theme of auspiciousness (maṅgalam; bkra
    shis) including verses of auspiciousness (maṅgalagāthā) and prayers:'
  volume:
    c12a4950652542c4b30a46e5a5faa45f:
      title: A Prayer for Auspiciousness
      parent: Verses of Auspiciousness
    0a45418dfec143ab87509011676dbb58:
      title: The Auspicious Verses of the Seven Successive Buddhas
      parent: Verses of Auspiciousness
    b8a54bc82bca4f0491a5f427f104a846:
      title: Verses of Auspiciousness
      parent: Verses of Auspiciousness
    2529929a38cf496d8a250cdecbbd29db:
      title: 'Virtuous Adornment for All the World: Verses to Bring Auspiciousness
        and Wellbeing'
      parent: Verses of Auspiciousness
    6e7a68f6a49a497da300b8212a0e6b01:
      title: Verses of the Eight Noble Auspicious Ones
      parent: Verses of Auspiciousness
created_at: '2022-03-01T02:52:02.799654'
last_modified_at: '2022-03-01T02:52:02.799657'
